server:
  servlet:
    context-path: /activity-registration

spring:
  application:
    name: study

---
server:
  port: 4051
spring:
  profiles: dev

---
server:
  port: 4051
spring:
  profiles: test

---
server:
  port: 4051
spring:
  profiles: prod
